// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWhuXFEyva2GAecG72lExFosgPKGb7Q8',
    appId: '1:319783963628:web:b6a3b5661f1a9fcd2f8ec9',
    messagingSenderId: '319783963628',
    projectId: 'notes-d6f4b',
    authDomain: 'notes-d6f4b.firebaseapp.com',
    storageBucket: 'notes-d6f4b.appspot.com',
    measurementId: 'G-4H2HDPBHWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8dimxgKvjUOKWhMwrC8kogkWrHD6Wqk',
    appId: '1:319783963628:android:38a5504dc2c78d952f8ec9',
    messagingSenderId: '319783963628',
    projectId: 'notes-d6f4b',
    storageBucket: 'notes-d6f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8y8wTc3FgQ3rHxr8fXwDDilqpd6h4MFM',
    appId: '1:319783963628:ios:405c4273d1fcc6df2f8ec9',
    messagingSenderId: '319783963628',
    projectId: 'notes-d6f4b',
    storageBucket: 'notes-d6f4b.appspot.com',
    iosBundleId: 'xyz.codesynth.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8y8wTc3FgQ3rHxr8fXwDDilqpd6h4MFM',
    appId: '1:319783963628:ios:cc2b2cd828a37c5c2f8ec9',
    messagingSenderId: '319783963628',
    projectId: 'notes-d6f4b',
    storageBucket: 'notes-d6f4b.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxWhuXFEyva2GAecG72lExFosgPKGb7Q8',
    appId: '1:319783963628:web:afa668b956abcf192f8ec9',
    messagingSenderId: '319783963628',
    projectId: 'notes-d6f4b',
    authDomain: 'notes-d6f4b.firebaseapp.com',
    storageBucket: 'notes-d6f4b.appspot.com',
    measurementId: 'G-5N89JRPQGJ',
  );
}
